DirectoryPath: "site"
IgnoreURLs:
  - m.carlosbecker.com
  - amzn.to
  - linkedin.com
  - fonts.gstatic.com
  - https://medium.com/production-ready
  - http://fgnass.github.com
  - hacktoberfest.joinville.br
  - gwtbootstrap.github.com
  - lg.com
  - www.paypal.com
  - https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md#proposal
  - rdio.com
IgnoreDirs: []
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
HTTPHeaders:
  "Range": "bytes=0-10"
  "Accept": "*/*"
