baseurl = "https://carlosbecker.com/"
languageCode = "en-us"
title = "Carlos Becker"
theme = "custom"
copyright = "© Carlos Alexandro Becker - 2012 - {year}"

disableAliases = true

[markup]
	[markup.highlight]
	codeFences = true
	guessSyntax = true
	style = "dracula"
	noClasses = true
	tabWidth = 2

[related]
	threshold = 80
	includeNewer = true
	toLower = true

	[[related.indices]]
		name = "keywords"
		weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
	post = "/posts/:slug"

[privacy]
	[privacy.twitter]
		enableDNT = true
	[privacy.youtube]
		privacyEnhanced = true

[params]
	author = "Carlos Alexandro Becker"
	authorBio = "Carlos is a Site Reliability Engineer who enjoys working on OpenSource."
	description = "Thoughts, rants and discoveries on software development and related stuff."
	keywords = "software development, software, golang, devops, go, sre, site reliability engineering, software engineering"
	avatar = "avatar.jpg"
	twitter = "caarlos0"
	github = "caarlos0"
	sponsors = "caarlos0"
	telegram = "caarlos0"
	email = "carlos@carlosbecker.dev"
	linkedin = "https://www.linkedin.com/in/caarlos0/"
	cover = "/cascavel.png"
	ogImage = "/og-image.png"
	hideComments = true

[params.plausible]
	domain = "carlosbecker.com"

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 10
	[[menu.main]]
		name = "Archive"
		url = "/archive"
		weight = 20
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		url = "/talks/"
		weight = 30
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 40

[outputs]
home = [ "HTML", "RSS" ]
